test: &default

  # Credentials for REST APIs
  client_id: AY1iAgtCjL2_-B9VfsiBr02agwe_R3z52M7HN9sqR48TOMyHowdBeir8LPZaDma6l4dOGHQNbaCo3J3D
  client_secret: EIDugJDXtgN0eIlNuBE4O6FkMhgsD0Y3Kl6anpaw_cmHoUgR8sEwEIcYoFpW1gm52bxUeAzB6pTgeHQ_

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  <<: *default

staging:
  <<: *default

production:
  client_id: ENV['REACT_APP_PAYPAL_CLIENT_ID_PRODUCTION']
  client_SECRET: ENV['PAYPAL_SECRET_PRODUCTION']
  mode: live
