---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [critical, 2]
  - default
  - low
  - mailers
:schedule:
  crypto_scraper_worker:
    cron: '54 * * * *' # Run every 1 hour starting at minute 54.
    class: CryptoScraperWorker

  node_pricer_worker:
    cron: '*/5 * * * *' # Run every 5 mins.
    class: NodePricerWorker

  node_rewarder_worker:
    cron: '16 2 * * *' # Run every day at 2:16 AM
    class: NodeRewarderWorker

  node_daily_ticker_worker:
    cron: '3 1 * * *' # Run every day at 1:03 AM
    class: NodeDailyTickerWorker
