---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [critical, 2]
  - default
  - low
  - mailers
:schedule:
  crypto_scraper_worker:
    cron: '53 * * * *' # Run every 1 hour starting at minute 53.
    class: CryptoScraperWorker

  node_pricer_worker:
    cron: '*/7 * * * *' # Run every 7 mins.
    class: NodePricerWorker

  node_rewarder_worker:
    cron: '16 2 * * *' # Run every day at 2:16 AM
    class: NodeRewarderWorker

  node_daily_ticker_worker:
    cron: '3 1 * * *' # Run every day at 1:03 AM
    class: NodeDailyTickerWorker

  site_map_worker:
    cron: '0 2 * * *' # Run every day at 2:00 AM
    class: SiteMapWorker

