---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [critical, 2]
  - default
  - low
  - mailers
:schedule:
  crypto_scraper_worker:
    cron: '54 * * * *' # Run every 1 hour starting at minute 54.
    class: CryptoScraperWorker

  node_pricer_worker:
    cron: '13,28,43,58 * * * *' # Run every 15 mins starting at minute 13.
    class: NodePricerWorker

  node_scraper_worker:
    cron: '16 2 * * *' # Run every day at 2:16 AM
    class: NodePricerWorker

  node_daily_ticker_worker:
    cron: '1 1 * * *' # Run every day at 1:01 AM
    class: NodeDailyTickerWorker
