---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [critical, 2]
  - default
  - low
  - mailers
:schedule:
  crypto_scraper_worker:
    cron: '24,54 * * * *' # Run every 30 mins starting at minute 24.
    class: CryptoScraperWorker

  node_pricer_worker:
    cron: '13,28,43,58 * * * *' # Run every 15 mins starting at minute 13.
    class: CryptoScraperWorker
