import React, { Component } from 'react'

import './index.css'
import { Container, Row, Col } from 'reactstrap'
import Metatags from "../metatags"

export default class Terms extends Component {
  componentDidMount() {
    // Reset to top of window.
    window.scrollTo(0, 0)
  }

  render() {
    return (
      <Container>
        <Metatags/>
        <Col xl={{ size: 8, offset: 2 }} lg={{ size: 8, offset: 2 }} md={{ size: 10, offset: 1 }} sm={{ size: 12, offset: 0 }} className="mb-5">
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pageTitle"> Terms Of Use</p>
            <p className="paragraphText">The use of services provided by Nodebucks (hereafter referred to as "NB") is subject to the following Terms and Conditions</p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseSectionTitle pb-2">Important Notice</p>
            <p className="paragraphText">Please email <a href="mailto:support@nodebucks.com">support@nodebucks.com</a> for all inquires.</p>
            <p className="paragraphText"><b>Party Definitions and Introductory Terms</b> - The operative parties referred to in this Agreement are defined as follows:</p>
            <ol>
              <li>
                <p className="paragraphText"> NB is the publisher and operator of www.nodebucks.com (the "Site") whereby NB makes certain Masternode services (the "Services") available. For purposes of this Agreement, when "Site" or "Services" are referenced, such reference includes all software and network resources necessary to provide said Site and/or Service.</p>
                <p className="paragraphText"> When first-person pronouns are used in this Agreement, (Us, We, Our, Ours, etc.) these provisions are referring to NB. Additionally, when the terms "the Site" or "Site" are used, these terms refer to any site published by Us, unless a site is specifically exempt from this policy.</p>
              </li>
              <li>
                <p className="paragraphText"><b>You, the Client</b> - As Our Client and the user of the Site or Services, this Agreement will refer to You through any second-person pronouns, such as "Your," "Yours," etc</p>
              </li>
            </ol>
            <p className="paragraphText text-uppercase">PLEASE READ THE FOLLOWING HOSTING SERVICES TERMS AND CONDITIONS. BY SUBSCRIBING TO NODEBUCKS’ SERVICES, YOU AGREE TO BE BOUND BY ALL THE TERMS AND CONDITIONS OF THIS AGREEMENT (the "AGREEMENT"). IF YOU AGREE WITH THE TERMS AND CONDITIONS OF THIS AGREEMENT, CLICK "I ACCEPT," (OR SIMILAR SYNTAX) OR CHECK THE APPROPRIATE BOX MANIFESTING YOUR INTENT TO BE BOUND BY THESE TERMS AND CONDITIONS AND CONTINUE WITH THE ACCOUNT SET-UP PROCESS. YOU
              SHOULD PRINT-OUT OR OTHERWISE SAVE A COPY OF THIS AGREEMENT FOR FUTURE REFERENCE. IF YOU DO NOT AGREE WITH ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, CLICK THE "BACK" BUTTON ON YOUR BROWSER AND DO NOT SUBSCRIBE TO NODEBUCKS’ SERVICES. NODEBUCKS AGREES TO PROVIDE SERVICES TO YOU ONLY IF YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS CONTAINED HEREIN. YOUR ELECTRONIC ACCEPTANCE OF THIS AGREEMENT IS PERMITTED BY THE ELECTRONIC SIGNATURES IN GLOBAL AND NATIONAL
              COMMERCE ACT (E-SIGN ACT) AND SIMILAR FEDERAL AND STATE LAWS. ANY USE OF VULTR'S SERVICES SHALL CONSTITUTE AN ACT OF ACCEPTANCE OF THE CURRENT HOSTING SERVICES TERMS AND CONDITIONS.</p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">1. SERVICES</p>
            <p className="paragraphText">1.1 At the time of initial registration, You will select from the list of available Services to which You wish to subscribe. All subscriptions to Services are subject to formal acceptance by NB. Your subscription to the Services will be deemed accepted by NB when NB delivers a confirmation of the subscription to You. NB reserves the right to refuse to provide You with any Service for any reason. Notwithstanding Our Uptime Guarantee found in Section 17 of
              this Agreement, NB also reserves the right to interrupt access to the Services to perform regular and emergency maintenance as needed. You may order additional Services at any time, provided that You agree to pay the then-current fees for such additional Services. All additional Services shall be considered "Services" hereunder. All Services provided are subject to availability and to all of the terms and conditions of this Agreement.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">We'll notify you right away once your services have been activated! </p>
            <p className="paragraphText">Unfortunately, we sometimes have to deny our services or interrupt them for maintenance. </p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">2. REVISIONS TO USER AGREEMENT</p>
            <p className="paragraphText">This Agreement contains the complete and entire terms and conditions that apply to Your use of NB’s Services (as defined below). NB may modify the terms of this Agreement, including the Fees (as defined below) at any time.</p>
            <p className="paragraphText"><b>2.1</b> From time to time, We may revise this Agreement. We reserve the right to do so, and You agree that We have this unilateral right. You agree that all modifications or changes to this Agreement are in force and enforceable immediately upon posting. The updated or edited version supersedes any prior versions immediately upon posting, and the prior version is of no continuing legal effect unless the revised version specifically refers to the prior
              version
              and keeps the prior version or portions thereof in effect. To the extent any amendment of this Agreement is deemed ineffective or invalid by any court, the parties intend that the prior, effective version of this Agreement be considered valid and enforceable to the fullest extent.</p>
            <p className="paragraphText"><b>2.2</b> We agree that if We change anything in this Agreement, We will change the "last modified date" at the top of this Agreement. You agree to periodically re-visit this web page, and to use the "refresh" button on Your browser when doing so. You agree to note the date of the last revision to this Agreement. If the "last modified" date remains unchanged from the last time You reviewed this Agreement, then You may presume that nothing in the
              Agreement has
              been changed since the last time You read it. If the "last modified" date has changed, then You can be certain that something in the Agreement has been changed.</p>
            <p className="paragraphText"><b>2.3</b> Should You wish to terminate this Agreement due to any revisions made by Us, You must do so in writing via the cancellation form within thirty (30) days of the "last modified" date described above. Your continued use of the Services after the effective date of any such notice constitutes Your acceptance of such changes.</p>
            <p className="paragraphText"><b>2.4</b> Waiver – if You fail to periodically review this Agreement to determine if any of the terms have changed, You assume all responsibility for such omission and You agree that such failure amounts to Your affirmative waiver of Your right to review the amended terms. We are not responsible for Your neglect of Your legal rights.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">Every so often, we have to update this agreement. Check the date at the top to see the last time it was revised.</p>
            <p className="paragraphText">Simply continue to use our services to show us that you accept the changes.</p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">3. DURATION OF AGREEMENT AND CANCELLATION POLICY</p>
            <p className="paragraphText"><b>3.1</b> The Initial Term shall begin upon confirmation of Your order or commencement of the Services to You and receipt of lawful funds. The term's length is chosen by You and shall be indicated when You order Our Services. This Agreement may not be terminated by You during the Initial Term (and any renewals thereof) except in the event of a breach by NB. After the Initial Term, this Agreement shall automatically renew for successive terms, equal in
              length to the Initial Term, unless terminated or canceled by either party as provided herein.</p>
            <p className="paragraphText"><b>3.2</b> NB may also terminate this Agreement in its sole discretion at any time for any reason or no reason. ("Termination without Cause"). In such case, NB will provide You with thirty (30) days written notice before the discontinuation of Services.</p>
            <p className="paragraphText"><b>3.3</b> If NB cancels this Agreement pursuant to any of the terms outlined in this Agreement, with the exception of Termination without Cause pursuant to paragraph 3.2, NB shall not refund to You any fees paid or prepaid in advance of such cancellation and You shall be obligated to pay all fees and charges accrued prior to the effectiveness of such cancellation. In the event that NB terminates the Agreement for cause, all prepaid service fees will be
              forfeited and are not refundable. The termination of this Agreement does not relieve You of Your obligation to pay any Fees accrued or payable to NB prior to the effective date of termination of this Agreement.</p>
            <p className="paragraphText"><b>3.4</b> In addition to NB’s right to terminate this Agreement provided elsewhere in this Agreement, NB may terminate this Agreement effective immediately if, based on NB's sole judgment, it determines that You or any of Your end-users: (a) have breached the Acceptable Use Policy ("AUP") as described in Section 12 of this Agreement, and incorporated herein, (b) have infringed or violated any intellectual property right or privacy or publicity right of a
              third party, (c) have not complied with any applicable law, statute or regulation, or (d) have uploaded, published or disseminated any images, text, graphics, code or video which NB considers illegal or high risk, in its discretion. Nothing contained in this Agreement is intended to, or shall, impose any duty or obligation upon NB to monitor or review Your Content or the content of Your end-users at any time. You remain solely responsible for Your Content, and any liability
              generated therefrom.</p>
            <p className="paragraphText"><b>3.5</b> The termination of this Agreement will terminate Your access to the Services and Your license to the Host Materials (as defined in Section 5.2 of this Agreement). NB shall not be liable to You or to any third party for termination of the Services permitted under this agreement. Upon termination of this Agreement, NB reserves the right to maintain copies of Your data files and records for archival purposes, but does not undertake any obligation
              to do so. NB reserves the right to impose an early termination charge for all Services terminated prior to the last day of the billing cycle.</p>
            <p className="paragraphText"><b>3.6</b> If either party cancels or terminates this Agreement for any reason, You shall be solely responsible for making all necessary arrangements for securing a replacement host and moving all electronic data, graphics, images, video or text to the new service provider. Upon termination of this Agreement, provisions that by their nature would be expected to survive termination shall survive and remain in full force and effect in accordance with their
              terms.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">We require that you keep your services running until after the initial term. NB reserves the right to cancel your services anytime, but we really don't want to! </p>
            <p className="paragraphText">Liabilities resulting from your content is your responsibility. If we have to cancel this agreement, it is up to you to move your content to another provider.</p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">4. ACCOUNT SET UP</p>
            <p className="paragraphText"><b>4.1</b> When You register for the Services, You will choose a login (email) and password. You may use the Services or modify Your data and content only through such user ID and password. You are entirely responsible for maintaining the confidentiality of Your user ID and password and for any and all activities which occur using those credentials. You agree to immediately notify Us of any unauthorized use of Your account or any other breach of security
              known to You.</p>
            <p className="paragraphText"><b>4.2</b> You must provide Us with a primary email address that is checked regularly and frequently. All notices and communications between Us will be sent to the email address You provide, and You are therefore required to keep this address current or notify Us if Your address changes. You should notify Us if any of Your contact and/or billing information changes so that We may update Your account. It is also Your responsibility to make sure that Our
              domain(s), nodebucks.com, are not included in any spam block list used by You or Your mail provider.</p>
            <p className="paragraphText"><b>4.3</b> Providing false or inaccurate contact information of any kind may result in the Termination for Cause of Your account per Section 3 of this Agreement.</p>
            <p className="paragraphText"><b>4.4</b> You are responsible for all activity transpiring under Your account. We therefore highly recommend that You secure file, directory, and script permissions to the most restrictive settings possible. You agree that You have the technical ability to properly operate a web site and that You are responsible for any actions performed under Your account, including but not limited to, damage caused to Your site, NB's site and/or equipment, and any
              other site.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">Keep your login credentials secure! </p>
            <p className="paragraphText">Please be sure to keep your email address updated too. We do most of our correspondence over email. </p>
            <p className="paragraphText">Also, be careful when giving out your account information. Any activity on your account is your responsibility. </p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">5. INTELLECTUAL PROPERTY RIGHTS</p>
            <p className="paragraphText">All Services provided by NB may only be used for lawful purposes.</p>
            <p className="paragraphText"><b>5.1</b> As between You and NB, NB acknowledges that it claims no proprietary rights in or to the content (including without limitation, text, software, music, sound, audio visual works, motion pictures, photographs, animation, video and graphics) supplied by You for use on Your web site ("Your Content"). You hereby grant to NB a non-exclusive, worldwide and royalty-free license to copy, make derivative works, display, perform, use, broadcast and
              transmit on and via the Internet Your Content, solely for the benefit of You and to enable NB to perform its obligations here-under</p>
            <p className="paragraphText"><b>5.2</b> In connection with performance of the Services and at the sole discretion of NB, NB may (but is not obligated to) provide You with certain materials, including, without limitation, computer software (in object code or source code form), data, documentation or information developed or provided by NB or its suppliers under this Agreement, domain names, electronic mail addresses and other network addresses assigned to You, and other know-how,
              methodologies, equipment, and processes used by NB to provide You with the Services ("Host Materials"). Subject to the terms and conditions of this Agreement, NB hereby grants You a limited, revocable, non-transferable, non-exclusive license to use the Host Materials solely in connection with the Services. This license terminates when this Agreement terminates. As between You and NB, You acknowledge and agree that NB owns all right, title, and interest or otherwise has acquired all
              applicable licenses for the masternodes, and all copyright, trade secret, patent, trademark and other intellectual property rights therein. Any use of services after termination of this Agreement is not licensed and strictly prohibited. You agree that You will not upload, transmit, reproduce, distribute or in any way exploit any materials obtained through the Services without first obtaining the express written permission to do so from NB.</p>
            <p className="paragraphText"><b>5.3</b> This Agreement does not constitute a license to use NB's trade names, service marks or any other trade insignia. Any use of any of NB’s trade names, service marks or any other trade insignia is strictly prohibited, absent NB's prior written consent.</p>
            <p className="paragraphText"><b>5.4</b> If We are required to enlist the assistance of an Attorney or other person to collect any liquidated damages or any other amount of money from You, or if We are required to seek the assistance of an Attorney to pursue injunctive relief against You, or if We are required to file an ICANN complaint against You in order to bring about the transfer of an offending URL to Us from You, then You additionally agree that You will reimburse Us for all
              fees incurred in order to collect these liquidated damages, or in order to seek injunctive relief from You, or in order to file and prosecute an ICANN complaint.</p>
            <p className="paragraphText"><b>5.5</b> You understand that even a nominal amount of damages may require the expenditure of extensive legal fees, travel expenses, costs, and other amounts that may dwarf the liquidated damages themselves. You agree that You will pay all of these fees and costs.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">All of your content belongs to you - not NB! You are simply granting NB permission to link your content to the internet. </p>
            <p className="paragraphText">If we end up providing you with any additional software, the terms of this agreement apply to it. </p>
            <p className="paragraphText">We hope that you love the NB service, but there are some legal boundaries when it comes to using our names and trademark. Reach out to us before doing so.</p>
            <p className="paragraphText">Misuse of our service can be costly to us. If misuse ends in damages, you may have to reimburse our legal fees. </p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">6. PAYMENT</p>
            <p className="paragraphText"><b>6.1</b> Payment for Services is due at time of purchase. Service fees are automatically withdrawn from your rewards payments.</p>
            <p className="paragraphText"><b>6.2</b> Unless separately negotiated by You and Us, and confirmed by separate written agreement, the initial and recurring Fees for the Services selected by You shall be as provided in the initial on-line order form. All set-up fees and special programming fees are non-refundable. Fees for Services are payable in advance. Failure to make payment of Fees for Services when due may result in the suspension or termination of Services.</p>
            <p className="paragraphText"><b>6.3</b> At the time of registration, You must select a payment method. NB reserves the right to contract with a third party to process all payments. Such third party may impose additional terms and conditions governing payment processing. If You do not pay all Fees when due, Your account will be deemed past due. For any past due Fees, NB will charge You interest at one and one-half percent (1.5%) or the highest rate allowed by applicable law,
              whichever is lower, per month of the unpaid amount, until paid.</p>
            <p className="paragraphText"><b>6.4</b> You agree to pay any and all taxes, including personal property, value added, or sales taxes, resulting from Your use of the Services. NB is not responsible for any bank fees incurred by You due to Your use of check cards, automatic payment services, insufficient funds, and any and all other fees your financial institution may impose due to Your use of the Services. If NB should receive less than full payment of the Fees due to taxes, bank
              charges, transfer fees, or the like, NB will invoice You for the difference between payment received and the Fees due.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">Fees for services are due in advance. It helps us keep our network running.</p>
            <p className="paragraphText">You can sell your server at any time at the market rate.</p>
            <p className="paragraphText">Depending on where you are located, taxes may be applicable to our services. These will be included in the cost.</p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">7. UPTIME AND BLOCKCHAIN GUARANTEE</p>
            <p className="paragraphText"><b>7.1</b> You agree that Your use of NB's Services is at Your own risk. Should the Coin Provider have issues, including but not limited to, not providing rewards, account corruption, security breaches, NB cannot be held responsible.</p>
            <p className="paragraphText"><b>7.2</b> Should a blockchain “Hard-Fork” occur, your rewards may be interrupted and/or lost for a period of up to 30 days.</p>
            <p className="paragraphText"><b>7.3</b> NB reserves the right to terminate support for a Masternode blockchain and/or coin at any time for any reason. If at that time you do not want to sell your Masternode, we will transfer over to your care. </p>
            <p className="paragraphText"><b>7.4</b> NB cannot guarantee 100% uptime and no refunds, rebates, or credits will be issued in these circumstances. If a Masternode does go offline, we will work hard and swiftly to make sure it is back online as soon as possible. </p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">We do our best to keep your masternodes online as much as possible. Since we profit when you profit, our incentives are aligned to ensure you profit from the blockchain rewards as often as possible. We are not responsible for 51% attacks, blockchain hard forks, or other 3rd party blockchain issues that are outside of our control. </p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">8. INDEMNIFICATION</p>
            <p className="paragraphText">You agree to defend, indemnify, and hold NB and its Affiliates harmless from and against any and all claims and liabilities, including reasonable attorneys' and experts' fees, related to or arising from (a) any breach of Your covenants under this Agreement; (b) Your use of the Services; (c) any defamatory, libelous or illegal material contained within Your Content or Your information and data; (d) any claim or contention that Your Content or Your information and data infringes any third party's patent, copyright or other intellectual property rights or violates any third party's rights of privacy or publicity; (e) any third party's access or use of Your Content or Your information and data; (f) any violation of the applicable Acceptable Use Policy. In the event of a claim under this section, NB shall be permitted to select legal counsel to provide a defense to such claim. NB reserves the right, at its own expense, to participate in the defense of any matter otherwise subject to indemnification from You, but shall have no obligation to do so. You shall not settle any such claim or liability without the prior written consent of NB, which shall not be unreasonably withheld.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">Should you break our agreement, you will hold NB and its affiliates harmless for liability. </p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">9. NO WARRANTIES</p>
            <p className="paragraphText">YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE AND EXCLUSIVE RISK. THE SERVICES ARE PROVIDED ON AN "AS IS, WITH ALL FAULTS" AND "AS AVAILABLE" BASIS. NB EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. OTHER THAN AS SET FORTH IN PARAGRAPH 11, NB MAKES NO WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS, OR THAT THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR FREE; NOR DOES NB MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES OR AS TO THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SERVICES OR THAT DEFECTS IN ANY SOFTWARE, HARDWARE OR THE SERVICES WILL BE CORRECTED. ANY STATEMENTS MADE REGARDING SUCH MATTERS IN PROMOTIONAL MATERIALS SHALL BE CONSIDERED ADVERTISING REFERENCES, AND NOT WARRANTIES. YOU UNDERSTAND AND AGREE THAT ANY USE YOU MAKE OF ANY MATERIAL AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS AT YOUR OWN DISCRETION AND RISK, AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL AND/OR DATA.</p>
            <p className="paragraphText">NB MAY MAKE THIRD-PARTY GOODS, SERVICES AND/OR SOFTWARE AVAILABLE TO YOU THAT ARE NOT PART OF THE SERVICES ("THIRD-PARTY SERVICES"). NB HAS NO CONTROL OVER THE CONTENT OF THIRD-PARTY SERVICES. USE OF ANY THIRD-PARTY SERVICES WILL BE AT YOUR OWN AND SOLE RISK AND SUBJECT TO THE TERMS AND CONDITIONS OF A SEPARATE AGREEMENT BETWEEN YOU AND THE THIRD-PARTY.</p>
            <p className="paragraphText">NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM NB OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY, WHETHER BY IMPLICATION, ESTOPPEL OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY MARKETING OR PROMOTIONAL MATERIALS DESCRIBING THE SERVICES ON NB'S WEBSITE.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">We strive to provide you with the best possible service, but we cannot include a warranty.</p>
          </Row>
          <Row className="pt-4 flex-column">
            <p className="termOfUseTitle pb-2">10. GENERAL PROVISIONS</p>
            <p className="paragraphText"><b>23.1</b> Jurisdiction, Venue, and Choice of Law. This Agreement and all matters arising out of or otherwise relating to this Agreement shall be governed by the laws of the State of California, excluding its conflict of law provisions. The parties hereby submit to the personal jurisdiction of the state and federal courts of San Jose, California in the event litigation permitted under this Agreement is initiated. Exclusive venue for any litigation permitted under this Agreement shall be with the state and federal courts located in San Jose, California.</p>
            <p className="paragraphText">The parties agree that this choice of venue, jurisdiction, and forum as set out in the following parts of this Agreement is mandatory and not permissive in nature, thereby precluding any possibility of litigation between the parties with respect to, or arising out of, this Agreement in jurisdiction other than that specified in this Section.</p>
            <p className="paragraphText">All parties hereby waive any right to assert the doctrine of forum non-conveniens or similar doctrines, or to object to venue with respect to any proceeding brought in accordance with this paragraph or with respect to any dispute under this Agreement whatsoever.</p>
            <p className="paragraphText">Each party hereby authorizes and accepts service of process sufficient for personal jurisdiction in any action against it, as contemplated by this paragraph by registered or certified mail, Federal Express, proof of delivery or return receipt requested, to the parties address for the giving of notices as set forth in this Agreement.</p>
            <p className="paragraphText"><b>23.2</b> Arbitration. If there is a dispute between the parties arising out of or otherwise relating to this Agreement, the parties shall meet and negotiate in good faith to attempt to resolve the dispute. If the parties are unable to resolve the dispute through direct negotiations, then, except as otherwise provided herein, either party shall submit the issue to binding arbitration in accordance with the then-existing Commercial Arbitration Rules of the American Arbitration Association. Arbitral Claims shall include, but are not limited to, contract and tort claims of all kinds, and all claims based on any federal, state or local law, statute, or regulation, excepting only claims under applicable worker's compensation law, unemployment insurance claims, intellectual property claims, actions for injunctions, attachment, garnishment, and other equitable relief. The arbitration shall be conducted in San Jose, California and conducted by a single arbitrator, knowledgeable in Internet and e-Commerce. Except as provided below, the party bringing the action shall be responsible for paying all costs for arbitration, including the arbitrator's fees. Each party shall bear its own attorneys' fees (except if the matter is for the collection of a debt owed, the prevailing party shall be awarded its attorneys fees, all arbitration costs and arbitrator fees, in addition to all other applicable remedies). The arbitrator shall have no authority to award any punitive or exemplary damages; certify a class action; add any parties; vary or ignore the provisions of this Agreement, and shall be bound by governing and applicable law. The arbitrator shall be willing to execute an oath of neutrality. The arbitrator shall render a written opinion setting forth all material facts and the basis of his or her decision within thirty (30) days of the conclusion of the arbitration proceeding. THE PARTIES HEREBY WAIVE ANY RIGHTS THEY MAY HAVE TO TRIAL BY JURY IN REGARD TO ARBITRAL CLAIMS.</p>
            <p className="paragraphText"><b>23.3</b> Assignment. The rights and liabilities of the parties hereto will bind and inure to the benefit of their respective assignees, successors, executors, and administrators, as the case may be. Neither this Agreement nor any rights granted hereunder may be sold, leased, assigned or otherwise transferred, in whole or in part by You.</p>
            <p className="paragraphText"><b>23.4</b> Severability. If for any reason a court of competent jurisdiction or arbitrator finds any provision of this Agreement, or any portion thereof, to be unenforceable, that provision will be enforced to the maximum extent permissible and the remainder of this Agreement will continue in full force and effect.</p>
            <p className="paragraphText"><b>23.5</b> No Waiver. Failure by either party to enforce any provision of this Agreement will not be deemed a waiver of future enforcement of that or any other provision, and no waiver of one breach will constitute a waiver of subsequent breaches of the same or of a different nature.</p>
            <p className="paragraphText"><b>23.6</b> Complete Agreement. This Agreement (including all other policies incorporated herein) constitutes the entire agreement between the parties with respect to the Services, and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. No amendment to or modification of this Agreement will be binding unless in writing and signed by a duly authorized representative of both parties.</p>
            <p className="paragraphText"><b>23.7</b> Relationship Between the Parties. NB is an independent contractor; nothing in this Agreement shall be construed to create a partnership, joint venture or agency relationship between the parties.</p>
            <p className="paragraphText"><b>23.8</b> Non-Solicitation. Beginning upon commencement of the Services to You and continuing for a period of two (2) years after the termination of this Agreement or after any other cancellation or termination of Your account or Services with Us, You agree not to directly or indirectly, solicit, hire, contract, or otherwise employ any NB employee who was an employee during the term of this Agreement (including the Initial Term and any successive terms), to work for You or any other firm, person or business, of whatever character, corporate or otherwise.</p>
            <p className="paragraphText"><b>23.9</b> Headings. Section and subsection headings of this Agreement are inserted for convenience only and shall not be deemed to constitute a part hereof nor to affect the meaning thereof.</p>
            <p className="paragraphText"><b>23.10</b> Force Majeure. NB shall not be responsible for any failure to perform due to unforeseen circumstances or to causes beyond its reasonable control, including but not limited to: acts of God; war, riot, embargoes, acts of civil or military authority, or terrorism; fire, flood, earthquakes, hurricanes, tropical storms or other natural disasters; fiber cuts; strikes, or shortages in transportation, facilities, fuel, energy, labor or materials; failure of the telecommunications or information services infrastructure; hacking, SPAM, or any failure of a computer, server or software for so long as such event continues to delay NB's performance.</p>
            <p className="paragraphText"><b>23.11</b> Export. You understand and acknowledge that the software elements of the Host Materials may be subject to regulation by agencies of the U.S. Government, including the U.S. Department of Commerce, which prohibits export or diversion of software to certain countries and third parties. You will not assist or participate in any such diversion or other violation of applicable U.S. laws and regulations. You warrant that You will not license or otherwise permit anyone not approved to receive controlled commodities under applicable U.S. laws and regulations and that You will abide by such laws and regulations.</p>
            <p className="paragraphText"><b>23.12</b> Complaints – California Residents: The Complaint Assistance Unit of the Division of Consumer Services of the Department of Consumer Affairs may be contacted at: http://www.dca.ca.gov/online_services/complaints/consumer_complaint.shtml.</p>
            <p className="paragraphText"><b>23.13</b> Government Rights. The software elements of the Host Materials have been developed at private expense and are "commercial computer software" or "restricted computer software" within the meaning of the FARs, the DFARs, and any other similar regulations relating to government acquisition of computer software. Nothing contained herein will be deemed to: (i) grant any government agency any license or other rights greater than are mandated by statute or regulation for commercial computer software developed entirely at private expense, or (ii) restrict any government rights in any extensions or custom solutions provided hereunder and developed at government expense.</p>
            <p className="paragraphText"><b>23.14</b> Notices Electronic Communications. All notices permitted or required under this Agreement may be sent by e-mail, fax, express mail, mail, or registered mail to the e-mail address, fax number, or address most recently provided by You and will be effective upon transmission. Evidence of successful transmission shall be retained. Each of the parties may communicate with the other by electronic means as described in this Agreement. Each of the parties agrees to the following for all electronic communications: (i) The user identification of a sender, contained in an electronic communication, is legally sufficient to verify the sender's identity and the communication's authenticity; (ii) An electronic communication sent by You containing Your user identification establishes You as its originator and has the same effect as a document with Your written signature on it; and (iii) An electronic communication, or any computer printout of it, is valid proof of the validity of the original document of the electronic communication.</p>
            <p className="termOfUseSectionTitle">More simply put:</p>
            <p className="paragraphText">This section explains the laws and regulations applicable to this agreement.</p>
          </Row>
        </Col>
      </Container>
    )
  }
}
